;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[colors]
transparent = #77
background = #1e1e2e
foreground = #cdd6f4
primary = #cba6f7
secondary = #a6e3a1
alert = #f38ba8
