;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/top]
width =  100%
height = 24
padding = 2
background = ${colors.transparent}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.transparent}
border-bottom-color = ${colors.transparent}
fixed-center = true
line-size = 2

modules-left = left-rounded-menu menu right-triangle-menu left-divider i3 right-triangle systray
modules-center = left-rounded-date date right-rounded-date
modules-right = let-triangle cpu memory brightness pulseaudio network right-divider left-triangle-clock clock right-rounded-clock

font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "JetBrainsMono Nerd Font:size=12;3"
font-2 = "JetBrainsMono Nerd Font:size=14;4"
