;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/left-rounded]
type = custom/text
content = %{T3} %{T-}
content-foreground = ${colors.background}

[module/right-rounded]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

[module/right-triangle]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

[module/left-triangle]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

[module/left-divider]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

[module/right-divider]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.background}

# Menu
[module/left-rounded-menu]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.secondary}

[module/right-triangle-menu]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.secondary}

[module/menu]
type = custom/text
content = "󰣭 "
content-foreground = ${colors.background}
content-background = ${colors.secondary}
content-font = 2
click-left = rofi -show drun
# End Menu

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false

format = <label-state> <label-mode>

label-focused = 󰮯 %name%
label-focused-foreground = ${colors.primary}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-unfocused = 󰊠 %name%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-background = ${colors.background}
label-unfocused-padding = 1

label-empty = 󰊠 %name%
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background}
label-empty-padding = 1

label-visible = 󰊠 %name%
label-visible-foreground = ${colors.foreground}
label-visible-background = ${colors.background}
label-visible-underline = ${colors.secondary}
label-visible-padding = 1

label-urgent = 󰊠 %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

# Clock
[module/right-rounded-clock]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.foreground}

[module/left-triangle-clock]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.foreground}

[module/clock]
type = internal/date
interval = 1
date = %H:%M

format-prefix = "󱑂 "
label = %date%
label-foreground = ${colors.background}
format-prefix-foreground = ${colors.background}
format-background = ${colors.foreground}
# End Clock

# Date
[module/right-rounded-date]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.primary}

[module/left-rounded-date]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 60
date = %d %B %Y
date-alt = %A, %d %B %Y

format-prefix = " "
label = %date%
label-foreground = ${colors.background}
format-prefix-foreground = ${colors.background}
format-background = ${colors.primary}
# End Date

[module/cpu]
type = internal/cpu
interval = 2

format-prefix = " "
format-prefix-foreground = ${colors.alert}
format-background = ${colors.background}
format-padding = 1
label = %percentage:2%%

[module/memory]
type = custom/script
exec = free -m | awk 'NR==2{printf " %.1fGB", $3/1024}'
format-padding = 1
format-foreground = ${colors.secondary}
format-background = ${colors.background}

[module/brightness]
type = custom/script
exec = ~/.config/polybar/scripts/brightness.sh get
interval = 2

format-prefix-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 1
format-prefix = "󰃟 "
label = %output%

scroll-up = ~/.config/polybar/scripts/brightness.sh up
scroll-down = ~/.config/polybar/scripts/brightness.sh down

[module/pulseaudio]
type = internal/pulseaudio

# format
format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.background}
format-volume-padding = 1
label-volume = %percentage%%

# Volume icon
ramp-volume-0 = " "
ramp-volume-1 = " "

# Muted
format-muted = <label-muted>
format-muted-background = ${colors.background}
label-muted = " "
label-muted-foreground = ${colors.alert}
format-muted-padding = 1

[module/systray]
type = internal/tray
tray-position = right
tray-padding = 8
tray-size = 60%
tray-scale = 1.0

[module/network]
type = internal/network
; Find your interface name using the `ip link` command
interface = wlp3s0
interval = 3.0
accumulate-stats = true
unknown-as-up = true

; Formatting when connected to a network
format-connected = <label-connected>
format-connected-padding = 2
format-connected-background = ${colors.background}
; Click action calls nmcli or interactive tools inside raw formatting tags
label-connected = %{A1:$HOME/.config/rofi/scripts/nmcli.sh:}%{F#cdd6f4} %{F-} %essid:0:4:...% %{A}

; Formatting when disconnected
format-disconnected = <label-disconnected>
format-disconnected-padding = 2
format-disconnected-background = ${colors.background}
label-disconnected = %{A1:$HOME/.config/rofi/scripts/nmcli.sh:}%{F#f38ba8}󰖪 %{F-} disconnected %{A}

